name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12h
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: igorvv11
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 6
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_stargazers: yes
          plugin_repositories: yes
          plugin_repositories_featured: igorvv11/seu-repositorio
          output: github-metrics.svg  # Gera o arquivo SVG

      - name: Commit and push metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github-metrics.svg
          git commit -m "Update GitHub Metrics" || echo "No changes to commit"
          git push
